### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by xXNiceYT** [Wqrro/Vasar#1]
Plugin no work and ip can’t join

**Comment by JustTalDevelops** [comment]
i reproduce issue server not loading fix plz

**Comment by JustTalDevelops** [comment]
PLS FIX MY SERVER 4 RANSOM NOW ????????????????????????????

**Comment by JustTalDevelops** [comment]
MY SERVER FILE IS DYIN PLZ HELP

**Comment by Ghezin** [comment]
Errors?

**Comment by DidntPot** [comment]
OH NAW
