### ISSUE TITLE
How to setup bot duels

### ISSUE THREAD

**Issue by ProDev69** [Wqrro/Vasar#8]
How to setup bot duels

**Comment by ghost** [comment]
How to have esex

**Comment by ghost** [comment]
@ProDev69 https://github.com/DidntPot/Vasar-Practice **Re-read**

**Comment by CaptainMuder** [comment]
I dont know how to add bot pvp

**Comment by ProtectorYT364** [comment]
> How to have esex

First cut your penis 2nd done

**Comment by rac14** [comment]
> @ProDev69 https://github.com/DidntPot/Vasar-Practice **Re-read**

I added it in the arenas and added Gamemode ad nodebuff and its still not working bruh
